services:
  postgres:
    image: postgres
    container_name: postgres
    ports:
      - 5434:5432
    env_file:
      - ./sonore-events-back-end/.env
    volumes:
      - postgres-volume:/var/lib/postgresql/data

  node:
    container_name: node
    build: ./sonore-events-back-end
    ports:
      - 5000:5000
    depends_on:
      - postgres
    env_file:
      - ./sonore-events-back-end/.env

volumes:
  postgres-volume: